version: "3.8"
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: YourStrong@Passw0rd
      POSTGRES_DB: accountsdb
